### ISSUE TITLE
[MR] Mob Grinding Utils

### ISSUE THREAD

**Issue by Iophobic** [tolly765/MC-1.20.1-Pack#13]
**Mob Grinding Utils 1.20.1-1.1.0**

**Mob Grinding Utils(https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils/files/5131447)**
Honestly, I just wanted this for the Ender Inhibitor. So I can have an enderman farm in my base since the NoTeleport Module for RFTools doesn't work...

**Is this mod available for 1.20.1?**
- [x] Yes
- [ ] No

**Additional context**
No Dependencies

**Comment by tolly765** [comment]
Will look into putting this in for v1.3.0
