### ISSUE TITLE
[MR] KubeJS

### ISSUE THREAD

**Issue by Iophobic** [tolly765/MC-1.20.1-Pack#14]
**KubeJS-2001.6.5-build.7**

**[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/5268032)**
I was wondering if we can add another charm/body slot to the curios.

**Is this mod available for 1.20.1?**
- [x] Yes
- [ ] No

**Additional context**
[Pastebin to the script](https://pastebin.com/Dqe0m5aC)
[CuriosAPI Git for Commands](https://github.com/TheIllusiveC4/Curios/wiki/Commands)

**Dependences**
[Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/5137938)
[Rhino](https://www.curseforge.com/minecraft/mc-mods/rhino/files/4944325)

**Comment by tolly765** [comment]
Seems a tad overkill, but I can take a look at this later

**Comment by Iophobic** [comment]
It was mainly cause my jetpack takes up my body slot and I would like to place a different trinket without having to remove my jetpack. Exclude charm, I forgot I can just put my wireless crafting grid on my spell focus slot.

**Comment by Iophobic** [comment]
Isn't needed.
