### ISSUE TITLE
[MR] Simple Voice Chat

### ISSUE THREAD

**Issue by Iophobic** [tolly765/MC-1.20.1-Pack#15]
**Simple Voice Chat 1.20.1-2.5.13**

**[SVC](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/5309764)**

**Is this mod available for 1.20.1?**
- [x] Yes
- [ ] No

**Additional context**
Just wanted to have this added for when I'm not in vc and in another. Sometimes I'm too tired to actually type. If it isn't possible to put this then that is fine. I understand the discord is there but I'm not always up for joining the discord server but would still like to talk to you all without having to type. All the depens are optional. Also [Server setup for voice chat depending on which host](https://modrepo.de/minecraft/voicechat/wiki/server_setup_mc_hosting)

**Comment by tolly765** [comment]
![Screenshot_20240507-084715.png](https://github.com/tolly765/MC-1.20.1-Pack/assets/9297773/79acb299-c7fa-42aa-a426-4e69f23fbb51)


We're currently on budget hosting due to it being ~£17/mo cheaper...

As such, I don't think this one will happen anytime soon unfortunately
