### ISSUE TITLE
[MR] Refined Cooking

### ISSUE THREAD

**Issue by Iophobic** [tolly765/MC-1.20.1-Pack#4]
**Refined Cooking 1.20.1**

**[Link to the Mod (Preferably on Modrinth/CurseForge)](https://www.curseforge.com/minecraft/mc-mods/refined-cooking)**
If we are doing CFBH's then we def need this!

**Is this mod available for 1.20.1?**
- [x] Yes
- [ ] No

**Comment by tolly765** [comment]
Added in 1.2.0
