### ISSUE TITLE
[MR] Ars Creo

### ISSUE THREAD

**Issue by Iophobic** [tolly765/MC-1.20.1-Pack#6]
**Ars Creo 1.20.1**

**[Link to the Mod (Preferably on Modrinth/CurseForge](https://www.curseforge.com/minecraft/mc-mods/ars-creo))**

**Is this mod available for 1.20.1?**
- [x] Yes
- [ ] No

**Additional context**
Add any other context about the mod here

**Comment by tolly765** [comment]
Currently waiting for suggestions for 1.3.0 before adding this in.
Concerns over lag were also addressed in 1.2.0
