### ISSUE TITLE
[MR] AE2 THings

### ISSUE THREAD

**Issue by TonyFTW** [tolly765/MC-1.20.1-Pack#7]
**AE2 Things**

**(https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge)**

**Is this mod available for 1.20.1?**
- [X] Yes
- [ ] No

**This mod makes using AE2 more automatable/manageable**
Add any other context about the mod here

**Comment by tolly765** [comment]
Closed - User changed their mind
