### ISSUE TITLE
[MR] SNAD

### ISSUE THREAD

**Issue by Iophobic** [tolly765/MC-1.20.1-Pack#8]
**Snad 1.20.1**

**[Link to the Mod (Preferably on Modrinth/CurseForge)](https://www.curseforge.com/minecraft/mc-mods/snad-redstone-edition)**
MOAR SUGAR. AT FASTER RATE.

**Is this mod available for 1.20.1?**
- [x] Yes
- [ ] No

**Additional context**
Add any other context about the mod here

**Comment by tolly765** [comment]
Added in 1.2.0
